const fs = require('fs');
const path = require('path');
const archiver = require('archiver');

const targetBrowser = process.argv[2] || 'chrome'; // chrome oder firefox

const distManifestPath = path.join(__dirname, 'dist/manifest.json');

if (!fs.existsSync(distManifestPath)) {
    console.error('dist/manifest.json not found - run `vite build` first.');
    process.exit(1);
}

// IMPORTANT: dist/manifest.json is generated by @crxjs/vite-plugin from the
// build we just ran, so its content_scripts/js entries always point at the
// *actual* hashed filenames in dist/assets for *this* build.
//
// Previously this script copied a hand-maintained manifest.chrome.json /
// manifest.firefox.json over the top of it, which hardcoded old hashed
// filenames from a previous build. Every time the source changed (or even
// just on a routine rebuild, since content hashes change whenever file
// contents change), those hardcoded filenames stopped matching what was
// actually in dist/assets - so the packaged extension would silently ship
// a manifest that pointed at non-existent JS files, and the content
// scripts would simply fail to load in the browser.
//
// Fix: only merge in the handful of fields that legitimately differ per
// browser (name, author, browser_specific_settings for Firefox), and leave
// everything else - especially the content_scripts file lists - exactly as
// generated by this build.
const manifest = JSON.parse(fs.readFileSync(distManifestPath, 'utf8'));

if (targetBrowser === 'firefox') {
    const overridesPath = path.join(__dirname, 'manifest.firefox.overrides.json');
    if (fs.existsSync(overridesPath)) {
        const overrides = JSON.parse(fs.readFileSync(overridesPath, 'utf8'));
        Object.assign(manifest, overrides);
    }
    // Firefox's MV3 support requires background.scripts as a fallback
    // alongside background.service_worker (Chrome/Edge accept
    // service_worker alone) - without it, AMO's linter rejects the
    // submission outright: "BACKGROUND_SERVICE_WORKER_NOFALLBACK".
    if (manifest.background && manifest.background.service_worker && !manifest.background.scripts) {
        manifest.background.scripts = [manifest.background.service_worker];
    }
}

fs.writeFileSync(distManifestPath, JSON.stringify(manifest, null, 2));

const version = manifest.version;
// manifest.name is now a "__MSG_...__" placeholder (resolved live by the
// browser via _locales/*/messages.json, not at build time), so it can't
// be used directly for the zip filename anymore - use a fixed name
// instead of whatever literal string happens to be in the manifest.
const cleanName = 'AutoDarts-Plus';
const browserLabel = targetBrowser.charAt(0).toUpperCase() + targetBrowser.slice(1);
const fileName = `${cleanName}-${version}-${browserLabel}.zip`;

const output = fs.createWriteStream(fileName);
const archive = archiver('zip', { zlib: { level: 9 } });

output.on('close', () => {
    console.log(`✅ ZIP erstellt: ${fileName} (${archive.pointer()} bytes)`);
});

archive.on('error', (err) => { throw err; });
archive.pipe(output);
archive.directory('dist/', false);
archive.finalize();
