name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: yarn install

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -p "try { require('./public/manifest.json').version } catch { require('./manifest.json').version }")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Chrome Extension
        run: yarn build:chrome

      - name: Zip Chrome Build
        run: |
          mkdir -p release
          cd dist && zip -r ../release/AutoDarts-Plus-${{ env.VERSION }}-Chrome.zip * && cd ..

      - name: Build Firefox Extension
        run: yarn build:firefox

      - name: Zip Firefox Build
        run: |
          cd dist && zip -r ../release/AutoDarts-Plus-${{ env.VERSION }}-Firefox.zip * && cd ..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AutoDarts-Plus-Builds
          path: release/
